name: Test & Deploy GlueJobs

on: [push]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Cache Docker Registry
        uses: actions/cache@v3
        with:
          path: /tmp/docker-registry
          key: docker-registry-${{ hashFiles('docker-compose.yml') }}
      - name: prepare container
        run: |
          docker-compose up -d
      - name: test
        run: |
          bash run_test.sh
