name: Test & Deploy GlueJobs

on: [push]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: lunch container
        run: |
          docker-compose up -d
      - name: test
        run: |
          bash run_test.sh
